Maven
ome/.github pull request #14
Opened 2020-11-18 16:51 UTC by jburel

Add template to build using Maven
This has been tested in the BF repo see https://github.com/jburel/bioformats/actions/runs/370615843

2020-11-26 08:58 UTC, sbesson requested changes
One immediate suggestion to add `pom.xml` to the JSON description.

Tested in a few context of a few repositories.
- [minimal-omero-client](https://github.com/ome/minimal-omero-client/actions/runs/381054924(
- [bio-formats-examples](https://github.com/sbesson/bio-formats-examples/runs/1457843323)
- [ome-codecs](https://github.com/sbesson/ome-codecs/actions/runs/384846016)

Other repositories will need extra customizations:
- [ome-common-java](https://github.com/sbesson/ome-common-java/actions/runs/379879610) requires infrastructure to run the S3 tests on some platforms 
- [ome-model](https://github.com/sbesson/ome-model/actions/runs/384856871) has some Python requirements

A ralted question is whether you see the Maven deployment happening as part of this template or in a separate template running on tags like PyPI? For reference, we have 2 strategies depending on the target repository:
- for  OME Artifactory deployment, a `deploy` phase was following the Travis build phases and running `mvn deploy` with a secret
- for OSS Sonatype deployments, the process was carried out manually with the signed GPG key

2020-11-26 08:58 UTC, sbesson commented on workflow-templates/maven.properties.json
> +    ]
I think we can assume any target repo will have a top-level POM

```suggestion
    ],
    "filePatterns": [
        "pom.xml$"
    ]
```

2020-11-26 09:07 UTC, jburel commented
I think we should split the "deployment" step and the "build" from the template.
Some packages e.g. minimal-omero-client do not need the deployment step.

2020-11-26 09:13 UTC, jburel commented
Some repos won't be able to use the template as such. The same is true for the gradle template e.g. https://github.com/ome/omero-blitz

2020-11-26 09:25 UTC, joshmoore commented
> I think we should split the "deployment" step and the "build" from the template.

If the one workflow won't be a single solution, then might be worth renaming. Have we split the two procedures in the other ecosystems as well?

2020-11-26 09:29 UTC, jburel commented
Gradle for example does not have yet any deployment
Publishing to several locations (as we discussed) e.g. artifactory and sonatype. This could make the template a bit convoluted and might not work depending on the actions used.

2020-11-29 21:07 UTC, sbesson commented
Summarizing briefly a conversation with @jburel:
- for Python, the Tox-based workflow is certainly different from the deployment workflow. This is largely motivated by the fact different build targets are used i.e. install vs sdist/bdist_wheel
- for Maven projects however, the `deploy` target is at the end of the Maven lifecyle so a separate deployment job would re-execute most of the steps of the build job. From my side both a combined multi-step workflow as well as separate build vs publication workflows are conceivable and have advantages and trade-offs.
- assuming separate workflows, what would be the name of the publication worklfow? `publish_maven`? `maven_deploy`? `publish_{artifactory,ossrh}`?
- similar decisions will likely be made for Gradle-based Java projects

2020-12-01 17:15 UTC, jburel commented
One option could be have a flag at the top of the template indicating the desired deployment target e.g. push artifact to GH
push artifact to artifactory, ossh.

2020-12-01 17:27 UTC, jburel commented
I will list this for review since some repositories that do not need deployment steps could benefit from that template as it is

2020-12-01 21:31 UTC, jburel commented
tested the GH publishing option in https://github.com/ome/omero-downloader/pull/46

2020-12-02 10:56 UTC, sbesson approved these changes
Think this is a great start. Understanding this template might be expanded to cover publication release steps - see https://github.com/ome/omero-downloader/pull/46, happy to get this merged it and start apply it to the relevant repositories. The main disadvantage is that it might involve a wave of workflow updates. @joshmoore any concern or additional thoughts?

2020-12-03 09:19 UTC, joshmoore approved these changes
Nope, none as it stands. I can see getting this in a propagating or trying to get the uploading handled to only need to rollout once.

2020-12-04 14:26 UTC, sbesson commented
Understood, immediately I'll start rolling this out to the Maven repositories deployed on OSSRH since there was no equivalent and we still need to investigate this publishing strategy.

2020-12-04 14:26 UTC, merged